### ISSUE TITLE
Clarify reupload possibility

### ISSUE THREAD

**Issue by rgaudin** [openzim/librechef#8]
We've seen that re-running the scraper with same params lead to errors of unauthorized re-upload.

We need to know exactly how upload/reupload works, what is possible, what are the limits and where those are so we can adjust our refresh strategy

**Comment by satyamtg** [comment]
Looking at the test run option, I do see that the channel gets properly uploaded. If we run with same params, then only nodes that were changed get uploaded and the ones which didn't are kept intact. Upload/reupload is managed by ricecooker and hence shall not throw such strange behaviours. I'm looking into ricecooker docs and will update here.

**Comment by rgaudin** [comment]
OK, closing until we have a reprocase then.
